-- AlterTable
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "anilistEnabled" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "anilistClientId" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "anilistToken" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "anilistUsername" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "anilistAutoSync" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "readerDefaults" JSONB;
